import {NextResponse} from "next/server";
import {getOperationsContext,operationsError} from "../../../../src/lib/server/operationsAccess";
const fail=(e:unknown)=>{const x=operationsError(e);return NextResponse.json({error:x.message},{status:x.status})};
export async function POST(request:Request){try{const c=await getOperationsContext(request);if(!c.canAdmin)return NextResponse.json({error:"Solo el administrador puede configurar Operations Hub."},{status:403});const b=await request.json() as {type?:string;name?:string;address?:string;color?:string;description?:string;receivesUrgent?:boolean;defaultTeamId?:string;slaMinutes?:number;memberIds?:string[];coordinatorIds?:string[];completeSetup?:boolean};
 if(b.completeSetup){const{error}=await c.admin.from("wama_operations_setup").upsert({tenant_id:c.tenantId,completed_at:new Date().toISOString(),completed_by:c.profile.id,updated_at:new Date().toISOString()});if(error)throw error;return NextResponse.json({ok:true});}
 if(!b.name?.trim()||!b.type)return NextResponse.json({error:"Nombre obligatorio."},{status:400});const name=b.name.trim();
 if(b.type==="location"){const{data,error}=await c.admin.from("wama_operations_locations").insert({tenant_id:c.tenantId,name,address:b.address?.trim()||null,created_by:c.profile.id}).select("*").single();if(error)throw error;return NextResponse.json({ok:true,item:data});}
 if(b.type==="team"){const memberIds=[...new Set([...(b.memberIds||[]),...(b.coordinatorIds||[])])];if(memberIds.length){const{data:licensed}=await c.admin.from("wama_module_user_assignments").select("profile_id").eq("tenant_module_license_id",c.license.id).eq("status","active").in("profile_id",memberIds);if((licensed||[]).length!==memberIds.length)return NextResponse.json({error:"Todos los integrantes deben tener una licencia activa de Operations Hub."},{status:400});}const{data,error}=await c.admin.from("wama_operations_teams").insert({tenant_id:c.tenantId,name,color:b.color||"#00B8AE",description:b.description?.trim()||null,receives_urgent:Boolean(b.receivesUrgent),response_sla_minutes:Number(b.slaMinutes||1440),created_by:c.profile.id}).select("*").single();if(error||!data)throw error;if(memberIds.length)await c.admin.from("wama_operations_team_members").insert(memberIds.map(profile_id=>({team_id:data.id,profile_id,team_role:(b.coordinatorIds||[]).includes(profile_id)?"coordinator":"operator"})));return NextResponse.json({ok:true,item:data});}
 if(b.type==="category"){if(b.defaultTeamId){const{data:team}=await c.admin.from("wama_operations_teams").select("id").eq("id",b.defaultTeamId).eq("tenant_id",c.tenantId).maybeSingle();if(!team)return NextResponse.json({error:"El equipo predeterminado no pertenece a tu empresa."},{status:400});}const{data,error}=await c.admin.from("wama_operations_categories").insert({tenant_id:c.tenantId,name,default_team_id:b.defaultTeamId||null,sla_minutes:Number(b.slaMinutes||1440)}).select("*").single();if(error)throw error;return NextResponse.json({ok:true,item:data});}
 return NextResponse.json({error:"Tipo no válido."},{status:400});}catch(e){return fail(e)}}

export async function PATCH(request:Request){try{const c=await getOperationsContext(request);if(!c.canAdmin)return NextResponse.json({error:"Solo el administrador puede editar la configuración."},{status:403});const b=await request.json() as {type?:"location"|"team"|"category";id?:string;status?:"active"|"inactive";name?:string;address?:string;color?:string;description?:string;receivesUrgent?:boolean;slaMinutes?:number;defaultTeamId?:string|null;memberIds?:string[];coordinatorIds?:string[]};if(!b.type||!b.id)return NextResponse.json({error:"Datos incompletos."},{status:400});const table=b.type==="location"?"wama_operations_locations":b.type==="team"?"wama_operations_teams":"wama_operations_categories";const update:Record<string,unknown>={updated_at:new Date().toISOString()};if(b.name?.trim())update.name=b.name.trim();if(b.status)update.status=b.status;if(b.type==="location"&&b.address!==undefined)update.address=b.address.trim()||null;if(b.type==="team"){if(b.color)update.color=b.color;if(b.description!==undefined)update.description=b.description.trim()||null;if(b.receivesUrgent!==undefined)update.receives_urgent=b.receivesUrgent;if(b.slaMinutes)update.response_sla_minutes=b.slaMinutes;}if(b.type==="category"){if(b.defaultTeamId!==undefined)update.default_team_id=b.defaultTeamId||null;if(b.slaMinutes)update.sla_minutes=b.slaMinutes;}const{error}=await c.admin.from(table).update(update).eq("id",b.id).eq("tenant_id",c.tenantId);if(error)throw error;if(b.type==="team"&&b.memberIds){const ids=[...new Set([...(b.memberIds||[]),...(b.coordinatorIds||[])])];await c.admin.from("wama_operations_team_members").delete().eq("team_id",b.id);if(ids.length)await c.admin.from("wama_operations_team_members").insert(ids.map(profile_id=>({team_id:b.id,profile_id,team_role:(b.coordinatorIds||[]).includes(profile_id)?"coordinator":"operator"})));}return NextResponse.json({ok:true});}catch(e){return fail(e)}}
