"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Bot, Building2, Package2, ReceiptText, ShieldCheck, Users } from "lucide-react";
import EnterpriseShell from "../../src/components/enterprise/EnterpriseShell";
import { StatCard, StatusPill } from "../../src/components/enterprise/PortalUI";
import { getMyTenants } from "../../src/core/tenant";
import { getMyLicensingSummary } from "../../src/core/licensing/licensingService";
import type { LicensingSummaryRow } from "../../src/core/licensing/types";
import type { TenantWithMembership } from "../../src/core/tenant/TenantTypes";

type HomeData={tenant:TenantWithMembership;licenses:LicensingSummaryRow[]};
const modules=[
 {key:"operations",name:"Operations Hub",eyebrow:"Operación",description:"Casos, equipos, alertas y trabajo en terreno.",href:"/operations-hub",icon:ShieldCheck},
 {key:"expense",name:"Expense Hub",eyebrow:"Gastos",description:"Rendiciones, evidencias y aprobaciones.",href:"/expense-hub",icon:ReceiptText},
 {key:"sales",name:"Sales Hub",eyebrow:"Ventas",description:"Pipeline, clientes y oportunidades comerciales.",href:"/sales-hub/crm",icon:Package2},
] as const;
async function loadHome(){const[tenants,all]=await Promise.all([getMyTenants(),getMyLicensingSummary()]);const tenant=tenants[0];if(!tenant)throw new Error("No hay una empresa asociada al usuario.");return{tenant,licenses:all.filter(x=>x.tenant_id===tenant.id)} as HomeData;}
export default function CompanyHomePage(){const[data,setData]=useState<HomeData|null>(null),[error,setError]=useState("");useEffect(()=>{void loadHome().then(setData).catch(e=>setError(e instanceof Error?e.message:"No fue posible cargar el portal."))},[]);const used=useMemo(()=>data?.licenses.reduce((n,l)=>n+l.used_seats,0)||0,[data]),capacity=useMemo(()=>data?.licenses.reduce((n,l)=>n+l.seat_capacity,0)||0,[data]),trials=useMemo(()=>data?.licenses.filter(l=>l.license_status==="trial")||[],[data]);if(error)return <EnterpriseShell title="Inicio" subtitle="Resumen ejecutivo de tu empresa."><div className="rounded-3xl border border-red-200 bg-white p-7 text-red-700">{error}</div></EnterpriseShell>;if(!data)return <EnterpriseShell title="WAMA" subtitle="Cargando empresa."><div className="h-40 animate-pulse rounded-3xl bg-white"/></EnterpriseShell>;const enabled=modules.filter(m=>data.licenses.some(l=>l.module_key===m.key));return <EnterpriseShell title="WAMA" subtitle="Tu empresa y tus módulos WAMA.">
<div className="space-y-5 xl:hidden">
 <section className="rounded-[1.6rem] bg-[#0B0C0E] p-5 text-white"><div className="flex items-center gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white p-1 text-lg font-black text-black">{data.tenant.logoUrl?<img src={data.tenant.logoUrl} alt={`Logo de ${data.tenant.name}`} className="h-full w-full object-contain"/>:data.tenant.name.slice(0,2).toUpperCase()}</div><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#00E5D6]">Tu espacio de trabajo</p><h2 className="truncate text-2xl font-black">{data.tenant.name}</h2><p className="mt-1 text-xs text-[#AEB5BD]">Selecciona el módulo al que quieres entrar.</p></div></div></section>
 <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#008F87]">Mis módulos</p><h2 className="text-2xl font-black">¿Qué quieres gestionar?</h2></div><span className="text-xs font-bold text-[#69717D]">{enabled.length} activos</span></div><div className="grid gap-3">{enabled.map(m=>{const l=data.licenses.find(x=>x.module_key===m.key)!;const Icon=m.icon;return <Link key={m.key} href={m.href} prefetch={false} className="flex min-h-[108px] items-center gap-4 rounded-3xl border border-[#DCE1E6] bg-white p-4 shadow-[0_8px_24px_rgba(11,12,14,.04)]"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#DFFFFA] text-[#008F87]"><Icon className="h-6 w-6"/></span><span className="min-w-0 flex-1"><span className="block text-[10px] font-black uppercase tracking-[.14em] text-[#008F87]">{m.eyebrow}</span><strong className="mt-1 block text-xl">{m.name}</strong><span className="mt-1 line-clamp-1 block text-xs text-[#69717D]">{m.description}</span></span><span className="text-right"><StatusPill>{l.license_status==="trial"?`${l.trial_days_remaining} días`:"Activo"}</StatusPill><ArrowRight className="ml-auto mt-3 h-5 w-5 text-[#008F87]"/></span></Link>})}</div></section>
 <section className="grid grid-cols-2 gap-3"><Link href="/empresa/usuarios" className="rounded-3xl border bg-white p-4"><Users className="h-5 w-5 text-[#008F87]"/><strong className="mt-3 block">Usuarios</strong><span className="mt-1 block text-xs text-[#69717D]">Equipo y accesos</span></Link><Link href="/empresa/ia" className="rounded-3xl border bg-white p-4"><Bot className="h-5 w-5 text-[#008F87]"/><strong className="mt-3 block">WAMA AI</strong><span className="mt-1 block text-xs text-[#69717D]">Asistente empresarial</span></Link></section>
</div>
<div className="hidden space-y-7 xl:block">
 <section className="overflow-hidden rounded-[2rem] bg-[#0B0C0E] p-10 text-white"><div className="flex items-center justify-between gap-7"><div className="flex items-center gap-5"><div className="flex h-32 w-32 shrink-0 items-center justify-center overflow-hidden rounded-3xl bg-white p-2 text-3xl font-black text-black">{data.tenant.logoUrl?<img src={data.tenant.logoUrl} alt={`Logo de ${data.tenant.name}`} className="h-full w-full object-contain"/>:data.tenant.name.slice(0,2).toUpperCase()}</div><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#00E5D6]">Portal de empresa</p><h2 className="mt-2 text-4xl font-black">{data.tenant.name}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#B8C0C8]">Administra identidad, módulos, usuarios, facturación y seguridad desde un mismo lugar.</p><Link href="/empresa/perfil" className="mt-5 inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm font-black"><Building2 className="h-4 w-4"/>Modificar perfil de empresa</Link></div></div><StatusPill>{trials.length?`${trials.length} módulo${trials.length>1?"s":""} en prueba`:"Empresa activa"}</StatusPill></div></section>
 <div className="grid gap-4 lg:grid-cols-3"><StatCard label="Módulos habilitados" value={String(data.licenses.length)} detail="Productos contratados"/><StatCard label="Usuarios asignados" value={`${used}/${capacity}`} detail={`${Math.max(0,capacity-used)} cupos disponibles`}/><StatCard label="Pruebas activas" value={String(trials.filter(l=>l.trial_days_remaining>0).length)} detail="15 días por módulo"/></div>
 <section className="rounded-[2rem] border border-[#DCE1E6] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#008F87]">Módulos contratados</p><h3 className="mt-1 text-xl font-black">Acceso rápido</h3></div><Link href="/empresa/modulos" className="font-black text-[#008F87]">Gestionar</Link></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{enabled.map(m=>{const l=data.licenses.find(x=>x.module_key===m.key)!;return <Link key={m.key} href={m.href} prefetch={false} className="rounded-3xl bg-[#F5F7F8] p-5 transition hover:-translate-y-1"><div className="flex items-start justify-between gap-3"><strong className="text-lg">{m.name}</strong><StatusPill>{l.license_status==="trial"?`${l.trial_days_remaining} días`:"Activo"}</StatusPill></div><p className="mt-2 text-sm text-[#69717D]">{m.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#008F87]">Ingresar <ArrowRight className="h-4 w-4"/></span></Link>})}</div></section>
</div></EnterpriseShell>}
