"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

const stages=["Target account","First contact","Qualified lead","Proposal sent","Negotiation","Closing","Closed won","Closed lost","No califica"] as const;
type Stage=typeof stages[number]; type Currency="UF"|"USD"|"CLP"; type SaleType="Spot"|"Recurrente"|"Mixta";
type DealFile={id:string;file_name:string;mime_type:string;file_size:number;created_at:string};
type Deal={id:string;company:string;contact:string;email:string;phone:string;website:string;product:string;need:string;sale_type:SaleType;amount:number;currency:Currency;stage:Stage;probability:number;owner:string;source:string;comment:string;created_at:string;wama_sales_deal_files:DealFile[]};
type Settings={currency:Currency;products:string[];configured_at:string|null};
const probability:Record<Stage,number>={"Target account":10,"First contact":20,"Qualified lead":30,"Proposal sent":45,Negotiation:65,Closing:85,"Closed won":100,"Closed lost":0,"No califica":0};
const blank={company:"",contact:"",email:"",phone:"",website:"",product:"",need:"",saleType:"Recurrente" as SaleType,amount:0,stage:"Target account" as Stage,owner:"",source:"Contacto directo",comment:""};

export default function SalesHubCrmPage(){
 const[deals,setDeals]=useState<Deal[]>([]),[settings,setSettings]=useState<Settings|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[showNew,setShowNew]=useState(false),[selected,setSelected]=useState<Deal|null>(null),[form,setForm]=useState(blank),[pendingFiles,setPendingFiles]=useState<File[]>([]),[saving,setSaving]=useState(false),[query,setQuery]=useState(""),[dragged,setDragged]=useState<string|null>(null),[configCurrency,setConfigCurrency]=useState<Currency>("UF"),[productText,setProductText]=useState("");
 async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token||""}
 async function api(path:string,init:RequestInit={}){const t=await token();const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${t}`);if(init.body&&!(init.body instanceof FormData))headers.set("Content-Type","application/json");const response=await fetch(path,{...init,headers});const data=await response.json();if(!response.ok)throw new Error(data.error||"No se pudo completar la operación.");return data}
 async function load(){setLoading(true);setError("");try{const[s,d]=await Promise.all([api("/api/sales/settings"),api("/api/sales/deals")]);setSettings(s.settings);setDeals(d.deals||[]);if(s.settings){setConfigCurrency(s.settings.currency);setProductText((s.settings.products||[]).join("\n"))}}catch(e){setError(e instanceof Error?e.message:"Error")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>deals.filter(d=>`${d.company} ${d.contact} ${d.product} ${d.need}`.toLowerCase().includes(query.toLowerCase())),[deals,query]);
 const metrics=useMemo(()=>{const open=deals.filter(d=>!["Closed won","Closed lost","No califica"].includes(d.stage));const won=deals.filter(d=>d.stage==="Closed won"),lost=deals.filter(d=>d.stage==="Closed lost");return{open:open.length,won:won.length,lost:lost.length,total:open.reduce((s,d)=>s+Number(d.amount),0),weighted:open.reduce((s,d)=>s+Number(d.amount)*d.probability/100,0),rate:won.length+lost.length?Math.round(won.length/(won.length+lost.length)*100):0}},[deals]);
 function money(n:number,c=settings?.currency||"UF"){return c==="CLP"?new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n):`${new Intl.NumberFormat("es-CL").format(n)} ${c}`}
 async function saveSettings(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const products=productText.split(/\n|,/).map(x=>x.trim()).filter(Boolean);const r=await api("/api/sales/settings",{method:"PUT",body:JSON.stringify({currency:configCurrency,products})});setSettings(r.settings)}catch(e){setError(e instanceof Error?e.message:"Error")}finally{setSaving(false)}}
 async function createDeal(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await api("/api/sales/deals",{method:"POST",body:JSON.stringify({...form,currency:settings?.currency})});let deal:Deal=r.deal;for(const file of pendingFiles){const fd=new FormData();fd.append("dealId",deal.id);fd.append("file",file);const uploaded=await api("/api/sales/files",{method:"POST",body:fd});deal={...deal,wama_sales_deal_files:[...(deal.wama_sales_deal_files||[]),uploaded.file]}}setDeals(c=>[deal,...c]);setForm(blank);setPendingFiles([]);setShowNew(false)}catch(e){setError(e instanceof Error?e.message:"Error")}finally{setSaving(false)}}
 async function move(id:string,stage:Stage){const old=deals;setDeals(c=>c.map(d=>d.id===id?{...d,stage,probability:probability[stage]}:d));try{await api("/api/sales/deals",{method:"PATCH",body:JSON.stringify({id,stage})})}catch(e){setDeals(old);setError(e instanceof Error?e.message:"No se pudo mover")}}
 async function remove(id:string){if(!confirm("¿Eliminar este deal?"))return;try{await api(`/api/sales/deals?id=${id}`,{method:"DELETE"});setDeals(c=>c.filter(d=>d.id!==id));setSelected(null)}catch(e){setError(e instanceof Error?e.message:"Error")}}
 async function openFile(id:string){try{const r=await api(`/api/sales/files?id=${id}`);window.open(r.url,"_blank","noopener,noreferrer")}catch(e){setError(e instanceof Error?e.message:"Error")}}

 if(loading)return <main className="grid min-h-screen place-items-center bg-[#F5F6F7] font-black">Cargando Sales Hub…</main>;
 if(!settings)return <Setup currency={configCurrency} setCurrency={setConfigCurrency} productText={productText} setProductText={setProductText} saving={saving} error={error} onSubmit={saveSettings}/>;
 return <main className="min-h-screen bg-[#F5F6F7] text-[#0B0C0E]">
  <header className="sticky top-0 z-40 border-b bg-white/95"><div className="mx-auto flex max-w-[1800px] flex-col gap-4 px-5 py-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#00AFA4]">Sales Hub · {settings.currency}</p><h1 className="text-3xl font-black">CRM comercial</h1><p className="text-sm text-[#63708A]">Deals persistentes, productos configurados y documentos privados.</p></div><div className="flex flex-wrap gap-2"><Link href="/empresa" className="rounded-full border px-5 py-3 text-sm font-black">Volver a módulos</Link><Link href="/empresa/usuarios" className="rounded-full border px-5 py-3 text-sm font-black">Usuarios y licencias</Link><button onClick={()=>{setConfigCurrency(settings.currency);setProductText(settings.products.join("\n"));setSettings(null)}} className="rounded-full border px-5 py-3 text-sm font-black">Configurar ventas</button><button onClick={()=>setShowNew(true)} className="rounded-full bg-[#00E5D6] px-6 py-3 text-sm font-black">+ Nuevo deal</button></div></div></header>
  <section className="mx-auto max-w-[1800px] p-5"><div className="mb-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Metric label="Abiertos" value={String(metrics.open)}/><Metric label="Ganados" value={String(metrics.won)}/><Metric label="Perdidos" value={String(metrics.lost)}/><Metric label="Win rate" value={`${metrics.rate}%`}/><Metric label="Pipeline" value={money(metrics.total)}/><Metric label="Ponderado" value={money(metrics.weighted)}/></div>
   {error&&<div className="mb-4 rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</div>}
   <div className="mb-5 rounded-2xl border bg-white p-4"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa, contacto, producto o necesidad…"/></div>
   <div className="overflow-x-auto pb-6"><div className="grid min-w-[2340px] grid-cols-9 gap-4">{stages.map(stage=>{const list=filtered.filter(d=>d.stage===stage);return <section key={stage} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragged)void move(dragged,stage);setDragged(null)}} className="min-h-[560px] rounded-[1.6rem] border border-[#D7DBE0] bg-[#EEF2F5] p-3"><div className="mb-3 border-t-4 border-[#00E5D6] px-1 pt-3"><div className="flex justify-between gap-2"><h2 className="text-sm font-black uppercase">{stage}</h2><span className="rounded-full bg-white px-2 py-1 text-xs font-black">{probability[stage]}</span></div><p className="mt-1 text-xs text-[#63708A]">{list.length} deal(s)</p></div><div className="grid gap-3">{list.map(deal=><article key={deal.id} draggable onDragStart={()=>setDragged(deal.id)} onDragEnd={()=>setDragged(null)} className={`rounded-2xl border bg-white p-4 shadow-sm ${dragged===deal.id?"opacity-50":""}`}><div className="flex cursor-grab items-start gap-3 active:cursor-grabbing"><span className="text-xl" title="Arrastrar">☷</span><button className="min-w-0 flex-1 text-left" onClick={()=>setSelected(deal)}><h3 className="truncate text-sm font-black">{deal.company}</h3><p className="mt-1 line-clamp-2 text-xs text-[#63708A]">{deal.product||deal.need||"Sin detalle"}</p></button><span className="rounded-full bg-[#E6FFFC] px-2 py-1 text-xs font-black text-[#008F86]">{deal.probability}%</span></div><div className="mt-4 flex items-end justify-between"><span className="text-xs font-bold text-[#63708A]">{deal.sale_type}</span><strong>{money(Number(deal.amount),deal.currency)}</strong></div>{deal.wama_sales_deal_files?.length>0&&<button onClick={()=>setSelected(deal)} className="mt-3 text-xs font-black text-[#008F86]">📎 {deal.wama_sales_deal_files.length} archivo(s)</button>}</article>)}</div></section>})}</div></div>
  </section>
  {showNew&&<Modal title="Crear oportunidad" close={()=>setShowNew(false)}><form onSubmit={createDeal} className="grid gap-4 md:grid-cols-2"><Input label="Empresa"><input required className="input" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></Input><Input label="Producto o servicio"><select required className="input" value={form.product} onChange={e=>setForm({...form,product:e.target.value})}><option value="">Seleccionar</option>{settings.products.map(p=><option key={p}>{p}</option>)}</select></Input><Input label="Contacto"><input className="input" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></Input><Input label="Correo"><input type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Input><Input label="Teléfono"><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Input><Input label="Sitio web"><input className="input" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></Input><Input label={`Monto (${settings.currency})`}><input type="number" min="0" className="input" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></Input><Input label="Tipo de venta"><select className="input" value={form.saleType} onChange={e=>setForm({...form,saleType:e.target.value as SaleType})}><option>Spot</option><option>Recurrente</option><option>Mixta</option></select></Input><Input label="Etapa"><select className="input" value={form.stage} onChange={e=>setForm({...form,stage:e.target.value as Stage})}>{stages.map(s=><option key={s}>{s}</option>)}</select></Input><Input label="Responsable"><input className="input" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></Input><Input label="Adjuntos (máx. 15 MB c/u)"><input type="file" multiple className="input" onChange={e=>setPendingFiles(Array.from(e.target.files||[]))}/></Input><div className="md:col-span-2"><Input label="Necesidad / comentario"><textarea className="input min-h-24" value={form.need} onChange={e=>setForm({...form,need:e.target.value})}/></Input></div><div className="flex justify-end gap-3 md:col-span-2"><button type="button" onClick={()=>setShowNew(false)} className="rounded-full border px-6 py-3 font-black">Cancelar</button><button disabled={saving} className="rounded-full bg-[#00E5D6] px-7 py-3 font-black">{saving?"Guardando…":"Crear y guardar"}</button></div></form></Modal>}
  {selected&&<Modal title={selected.company} close={()=>setSelected(null)}><div className="grid gap-5 md:grid-cols-2"><Card title="Negocio"><Row label="Producto" value={selected.product||"Sin registrar"}/><Row label="Monto" value={money(Number(selected.amount),selected.currency)}/><Row label="Etapa" value={selected.stage}/><Row label="Responsable" value={selected.owner}/></Card><Card title="Contacto"><Row label="Nombre" value={selected.contact||"Sin registrar"}/><Row label="Correo" value={selected.email||"Sin registrar"}/><Row label="Teléfono" value={selected.phone||"Sin registrar"}/></Card><div className="md:col-span-2"><Card title="Archivos"><div className="grid gap-2">{selected.wama_sales_deal_files?.length?selected.wama_sales_deal_files.map(f=><button key={f.id} onClick={()=>void openFile(f.id)} className="flex justify-between rounded-xl border bg-[#F7F9FB] p-3 text-left text-sm font-bold"><span>📎 {f.file_name}</span><span>Abrir</span></button>):<p className="text-sm text-[#63708A]">No hay archivos adjuntos.</p>}</div></Card></div><div className="flex justify-end md:col-span-2"><button onClick={()=>void remove(selected.id)} className="rounded-full border border-red-200 bg-red-50 px-5 py-3 text-sm font-black text-red-600">Eliminar deal</button></div></div></Modal>}
  <style jsx global>{`.input{width:100%;border:1px solid #d7dbe0;border-radius:1rem;background:white;padding:.85rem 1rem;font-size:.9rem;font-weight:700;outline:none}.input:focus{border-color:#00afa4}`}</style>
 </main>
}

function Setup(p:{currency:Currency;setCurrency:(v:Currency)=>void;productText:string;setProductText:(v:string)=>void;saving:boolean;error:string;onSubmit:(e:FormEvent)=>void}){return <main className="min-h-screen bg-[#F5F6F7] p-5"><div className="mx-auto max-w-3xl py-12"><Link href="/empresa" className="text-sm font-black">← Volver al portal</Link><form onSubmit={p.onSubmit} className="mt-6 rounded-[2rem] border bg-white p-7 shadow-sm"><p className="text-xs font-black uppercase tracking-[.24em] text-[#00AFA4]">Configuración obligatoria</p><h1 className="mt-2 text-4xl font-black">¿Qué venderá tu empresa?</h1><p className="mt-3 text-[#63708A]">Antes de abrir el CRM, define los productos o servicios y la moneda que usará todo el pipeline.</p>{p.error&&<div className="mt-5 rounded-xl bg-red-50 p-4 font-bold text-red-700">{p.error}</div>}<div className="mt-7 grid gap-5"><Input label="Moneda"><select className="input" value={p.currency} onChange={e=>p.setCurrency(e.target.value as Currency)}><option value="UF">UF</option><option value="USD">Dólar estadounidense (USD)</option><option value="CLP">Pesos chilenos (CLP)</option></select></Input><Input label="Productos o servicios (uno por línea)"><textarea required className="input min-h-44" value={p.productText} onChange={e=>p.setProductText(e.target.value)} placeholder={'Ejemplo:\nArriendo de espacios\nPublicidad\nServicios de instalación'}/></Input><button disabled={p.saving} className="rounded-full bg-[#00E5D6] px-7 py-4 font-black">{p.saving?"Guardando…":"Guardar y programar CRM"}</button></div></form></div></main>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/65 p-4"><div className="my-6 w-full max-w-4xl rounded-[2rem] bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-6"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="rounded-full bg-[#EEF1F4] px-5 py-3 font-black">Cerrar</button></div><div className="p-6">{children}</div></div></div>}
function Input({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2"><span className="text-xs font-black uppercase tracking-[.14em] text-[#63708A]">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-black uppercase text-[#63708A]">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border p-5"><h3 className="mb-3 font-black">{title}</h3>{children}</div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b py-3 text-sm last:border-0"><span className="text-[#63708A]">{label}</span><strong className="text-right">{value}</strong></div>}
