"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";

export default function PilotAdminPage(){
 const [form,setForm]=useState({secret:"",companyName:"",ownerName:"",ownerEmail:""}); const [loading,setLoading]=useState(false); const [result,setResult]=useState(""); const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");setResult("");try{const r=await fetch("/api/pilot/provision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"No se pudo crear el piloto.");setResult(`Piloto creado para ${d.tenant.name}. Invitación enviada a ${d.ownerEmail}. Rendiciones de Gastos activo con 10 usuarios hasta ${new Date(d.tenant.trial_ends_at).toLocaleDateString("es-CL")}.`);setForm(v=>({...v,companyName:"",ownerName:"",ownerEmail:""}));}catch(err){setError(err instanceof Error?err.message:"Error inesperado");}finally{setLoading(false)}}
 return <main className="min-h-screen bg-[#0B0C0E] px-5 py-12 text-white"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-black text-[#00E5D6]">← Volver a WAMA</Link><div className="mt-8 rounded-[2rem] border border-white/10 bg-white/[.05] p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#00E5D6]">Administración interna</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Crear empresa piloto</h1><p className="mt-4 text-[#B9C0C8]">Activa Rendiciones de Gastos por 15 días, con hasta 10 usuarios para la empresa, y envía la invitación al administrador principal.</p><form onSubmit={submit} className="mt-8 grid gap-4"><Input label="Clave interna" type="password" value={form.secret} onChange={v=>setForm({...form,secret:v})}/><Input label="Empresa" value={form.companyName} onChange={v=>setForm({...form,companyName:v})}/><Input label="Nombre del responsable" value={form.ownerName} onChange={v=>setForm({...form,ownerName:v})}/><Input label="Correo del responsable" type="email" value={form.ownerEmail} onChange={v=>setForm({...form,ownerEmail:v})}/>{error&&<p className="rounded-xl bg-red-500/15 p-4 text-sm text-red-100">{error}</p>}{result&&<p className="rounded-xl bg-[#00E5D6]/15 p-4 text-sm text-[#BFFFF9]">{result}</p>}<button disabled={loading} className="mt-2 rounded-full bg-[#00E5D6] px-6 py-4 font-black text-[#0B0C0E] disabled:opacity-50">{loading?"Creando piloto…":"Crear y enviar invitación"}</button></form></div></div></main>
}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="grid gap-2"><span className="text-sm font-black">{label}</span><input required type={type} value={value} onChange={e=>onChange(e.target.value)} className="rounded-2xl border border-white/10 bg-[#14171B] px-4 py-4 outline-none focus:border-[#00E5D6]"/></label>}
