"use client";
import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, Loader2, Mail, Plus, RefreshCw, UserPlus, XCircle } from "lucide-react";
import { supabase } from "../../../app/lib/supabase";

type Team = { id: string; name: string };
type Invitation = { status: string; sent_at?: string | null; send_attempts?: number; last_error?: string | null } | null;
type User = { id: string; full_name: string; email: string; module_role: string; license_status: string; invitation: Invitation; teams: Array<{ id: string; name: string; role: string }> };
type Payload = { users: User[]; teams: Team[]; license: { used: number; capacity: number }; error?: string };
const roles = [{ value: "operations_admin", label: "Administrador" }, { value: "operations_coordinator", label: "Coordinador" }, { value: "operations_operator", label: "Operativo" }, { value: "operations_reporter", label: "Reportante" }, { value: "operations_observer", label: "Observador" }];

async function call(url: string, init?: RequestInit) {
  const { data, error } = await supabase.auth.getSession();
  if (error || !data.session) throw new Error("Sesión caducada. Vuelve a iniciar sesión.");
  const response = await fetch(url, {
    ...init,
    headers: { Authorization: `Bearer ${data.session.access_token}`, ...init?.headers },
  });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || "No fue posible completar la solicitud.");
  return body;
}

export default function OperationsUsersPanel() {
  const [data, setData] = useState<Payload | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(""), [open, setOpen] = useState(false);
  const [form, setForm] = useState({ fullName: "", email: "", moduleRole: "operations_operator", teamIds: [] as string[], coordinatorTeamIds: [] as string[] });
  async function load() { setError(""); try { setData(await call("/api/operations/users")); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar usuarios."); } }
  useEffect(() => { void load(); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); setBusy("invite"); setError(""); try { await call("/api/operations/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setForm({ fullName: "", email: "", moduleRole: "operations_operator", teamIds: [], coordinatorTeamIds: [] }); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo invitar."); } finally { setBusy(""); } }
  async function resend(profileId: string) { setBusy(profileId); setError(""); try { await call("/api/operations/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "resend", profileId }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo reenviar."); } finally { setBusy(""); } }
  async function changeRole(profileId: string, moduleRole: string) { setBusy(profileId); setError(""); try { await call("/api/operations/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "role", profileId, moduleRole }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cambiar el perfil."); } finally { setBusy(""); } }
  const remaining = Math.max(0, (data?.license.capacity || 0) - (data?.license.used || 0));
  return <div className="grid gap-5">
    <section className="rounded-[2rem] border border-[#DCE1E6] bg-white p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#008F87]">Usuarios de Operations</p><h2 className="mt-2 text-2xl font-black">Licencias, perfiles e invitaciones</h2><p className="mt-2 text-sm text-[#69717D]">Una persona consume un cupo aunque participe en varios equipos.</p></div><button onClick={() => setOpen(!open)} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#00E5D6] px-5 py-3 text-sm font-black"><UserPlus className="h-4 w-4"/>Enviar invitación</button></div>
      <div className="mt-5 rounded-2xl bg-[#F4F8F8] p-4"><div className="flex justify-between text-sm"><strong>{data?.license.used || 0} de {data?.license.capacity || 0} licencias utilizadas</strong><span>{remaining} disponibles</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#DDE8E7]"><div className="h-full bg-[#00B8AE]" style={{ width: `${Math.min(100, ((data?.license.used || 0) / Math.max(1, data?.license.capacity || 1)) * 100)}%` }}/></div></div>
    </section>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
    {open && <form onSubmit={invite} className="grid gap-4 rounded-[2rem] border border-[#A8DCD7] bg-white p-6"><h3 className="text-xl font-black">Nueva invitación</h3><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-black">Nombre completo<input required className="input" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })}/></label><label className="grid gap-2 text-sm font-black">Correo<input required type="email" className="input" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/></label></div><label className="grid gap-2 text-sm font-black">Perfil<select className="input" value={form.moduleRole} onChange={(e) => setForm({ ...form, moduleRole: e.target.value })}>{roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></label><div><p className="mb-2 text-sm font-black">Equipos iniciales</p><div className="grid gap-2 sm:grid-cols-2">{data?.teams.map((team) => <label key={team.id} className="flex items-center gap-3 rounded-2xl border p-3 text-sm font-bold"><input type="checkbox" checked={form.teamIds.includes(team.id)} onChange={(e) => setForm({ ...form, teamIds: e.target.checked ? [...form.teamIds, team.id] : form.teamIds.filter((id) => id !== team.id), coordinatorTeamIds: e.target.checked ? form.coordinatorTeamIds : form.coordinatorTeamIds.filter((id) => id !== team.id) })}/><span className="flex-1">{team.name}</span>{form.teamIds.includes(team.id) && <select value={form.coordinatorTeamIds.includes(team.id) ? "coordinator" : "operator"} onChange={(e) => setForm({ ...form, coordinatorTeamIds: e.target.value === "coordinator" ? [...new Set([...form.coordinatorTeamIds, team.id])] : form.coordinatorTeamIds.filter((id) => id !== team.id) })} className="rounded-xl border px-2 py-1 text-xs"><option value="operator">Integrante</option><option value="coordinator">Coordinador</option></select>}</label>)}</div></div><button disabled={busy === "invite" || remaining < 1} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#00E5D6] px-5 py-4 font-black disabled:opacity-40">{busy === "invite" ? <Loader2 className="animate-spin"/> : <Plus/>}{busy === "invite" ? "Creando y enviando…" : "Crear licencia y enviar invitación"}</button></form>}
    <section className="overflow-hidden rounded-[2rem] border border-[#DCE1E6] bg-white"><div className="divide-y">{data?.users.map((user) => { const pending = ["pending", "sent", "failed", "expired"].includes(user.invitation?.status || ""); const failed = user.invitation?.status === "failed"; return <article key={user.id} className="grid gap-4 p-5 lg:grid-cols-[1.2fr_.8fr_.8fr_auto] lg:items-center"><div><strong className="block">{user.full_name}</strong><span className="text-sm text-[#69717D]">{user.email}</span><div className="mt-2 flex flex-wrap gap-2">{user.teams.map((team) => <span key={team.id} className="rounded-full bg-[#EEF5F4] px-2 py-1 text-xs font-bold">{team.name} · {team.role === "coordinator" ? "Coordinador" : "Integrante"}</span>)}</div></div><select disabled={busy === user.id || user.module_role === "module_admin"} value={user.module_role} onChange={(e) => void changeRole(user.id, e.target.value)} className="input text-sm"><option value="module_admin">Owner / administrador</option>{roles.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select><div className={`rounded-2xl p-3 text-xs font-bold ${failed ? "bg-red-50 text-red-700" : pending ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{failed ? <XCircle className="mb-1 h-4 w-4"/> : pending ? <Mail className="mb-1 h-4 w-4"/> : <CheckCircle2 className="mb-1 h-4 w-4"/>}<span className="block">{failed ? "Envío fallido" : pending ? `Invitación ${user.invitation?.status === "sent" ? "enviada" : "pendiente"}` : "Usuario activo"}</span>{user.invitation?.sent_at && <span className="mt-1 block font-normal">{new Date(user.invitation.sent_at).toLocaleString("es-CL")}</span>}{user.invitation?.last_error && <span className="mt-1 block font-normal">{user.invitation.last_error}</span>}</div><button disabled={!pending || busy === user.id} onClick={() => void resend(user.id)} className="inline-flex items-center justify-center gap-2 rounded-full border px-4 py-3 text-xs font-black disabled:opacity-30">{busy === user.id ? <Loader2 className="h-4 w-4 animate-spin"/> : <RefreshCw className="h-4 w-4"/>}Reenviar</button></article>; })}{!data?.users.length && <p className="p-10 text-center text-sm text-[#69717D]">Aún no hay usuarios licenciados.</p>}</div></section>
  </div>;
}
