"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

export default function AcceptInvitePage(){const router=useRouter();const [ready,setReady]=useState(false);const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setReady(Boolean(data.session)));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setReady(Boolean(s)));return()=>data.subscription.unsubscribe()},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(password.length<8){setError("La clave debe tener al menos 8 caracteres.");return}if(password!==confirm){setError("Las claves no coinciden.");return}setLoading(true);const {error:upError}=await supabase.auth.updateUser({password});if(upError){setError(upError.message);setLoading(false);return}const {data:{user}}=await supabase.auth.getUser();if(user){await supabase.from("wama_profiles").update({status:"active",updated_at:new Date().toISOString()}).eq("auth_user_id",user.id);const {data:profile}=await supabase.from("wama_profiles").select("id").eq("auth_user_id",user.id).single();if(profile)await supabase.from("wama_tenant_memberships").update({status:"active",joined_at:new Date().toISOString()}).eq("profile_id",profile.id)}router.replace("/empresa")}
 return <main className="grid min-h-screen place-items-center bg-[#0B0C0E] p-5 text-white"><section className="w-full max-w-lg rounded-[2rem] border border-white/10 bg-white/[.05] p-8"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#00E5D6] text-2xl font-black text-black">W</span><p className="mt-6 text-xs font-black uppercase tracking-[.2em] text-[#00E5D6]">Invitación WAMA</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Crea tu clave</h1><p className="mt-3 text-sm leading-6 text-[#B8C0C8]">Tu empresa ya fue habilitada. Define una clave segura para ingresar al Portal Empresarial y Expense.</p>{!ready?<p className="mt-7 rounded-xl bg-amber-500/15 p-4 text-sm text-amber-100">Abre esta página desde el enlace original recibido por correo. Si el enlace expiró, solicita una nueva invitación.</p>:<form onSubmit={submit} className="mt-7 grid gap-4"><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nueva clave" className="rounded-2xl border border-white/10 bg-[#15181C] px-4 py-4 outline-none focus:border-[#00E5D6]"/><input type="password" required value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repetir clave" className="rounded-2xl border border-white/10 bg-[#15181C] px-4 py-4 outline-none focus:border-[#00E5D6]"/>{error&&<p className="rounded-xl bg-red-500/15 p-3 text-sm text-red-100">{error}</p>}<button disabled={loading} className="rounded-full bg-[#00E5D6] px-6 py-4 font-black text-black">{loading?"Activando…":"Activar mi cuenta"}</button></form>}</section></main>}
